
NET_MODE="bond"        # bond | single | auto
NET_IFACES="eth0 eth1"
NET_EXCLUDE="lo docker0"
NET_DHCP="false"

IP_ADDR="192.168.10.230"
NETMASK="255.255.255.0"
GATEWAY="192.168.10.253"
DNS="192.168.10.252"
